### ISSUE TITLE
Update for 2.5.33

### ISSUE THREAD

**Issue by daerSeebaer** [daerSeebaer/choco-urbackup-server#5]
URL: https://hndl.urbackup.org/Server/2.5.33/UrBackup%20Server%202.5.33.exe

**Comment by Fabi1926** [comment]
Is there any timeline for this to happen? :)

**Comment by daerSeebaer** [comment]
resolved in https://github.com/daerSeebaer/choco-urbackup-server/commit/503c90f7369b04a1e32944413d3e0b0f46e5250a
